apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
      - name: timesheet-container
        image: techsopiankit/timesheetapplication2:timesheetimage
        ports:
        - containerPort: 9091
